services:
  requirements:
    build:
      context: docker/requirements
    volumes:
      - ./requirements:/requirements
      - ./.home/requirements:/home/app
    env_file:
      - .env

  test:
    extends:
      service: python
      file: docker-compose.common.yml
    build:
      args:
        REQUIREMENTS: test
        DJANGO_SETTINGS_MODULE: 'testbench_project.settings_test'
    entrypoint: /app/tests/entrypoint.sh
    environment:
      PYTHONPATH: /app/src:/app/tests
      DJANGO_DEBUG:
      DJANGO_DEBUG_SQL:
      DJANGO_DEBUG_SQL_LIMIT:
      PYTHONHUNTER:
      PYTHONHUNTERCONFIG:
      SERVER_NAME: localhost
      DJANGO_SECRET_KEY: test123
      SENTRY_DSN: ''
    stop_signal: SIGINT
    depends_on:
      - nginx
    volumes:
      - ./:/app
      - ./.home:/var/app

  uwsgi:
    extends:
      service: python
      file: docker-compose.common.yml
    env_file:
      - .env
    volumes:
      - ./.home/run:/var/app/run
    command: [
      uwsgi,
      --disable-logging,
      --ini=/etc/app/uwsgi.ini,
      --processes=10,
    ]

  uvicorn:
    extends:
      service: python
      file: docker-compose.common.yml
    command: [
      pysu, app, --,
      uvicorn,
      --http=httptools,
      --loop=uvloop,
      --uds=/var/app/run/uvicorn.sock,
      --workers=10,
      --ws=none,
      testbench_project.asgi:application,
    ]

  granian:
    extends:
      service: python
      file: docker-compose.common.yml
    command: [
      granian,
      --backlog=2048,
      --backpressure=1024,
      --http=1,
      --interface=asgi,
      --log-level=info,
      --loop=uvloop,
      --no-ws,
      --runtime-blocking-threads=10,
      --uds=/var/app/run/granian.sock,
      --workers=10,
      testbench_project.asgi:application,
    ]

  nginx:
    extends:
      service: python
      file: docker-compose.common.yml
    build:
      args:
        REQUIREMENTS: nginx
    volumes:
      - ./.home/etc:/shared/${SERVER_NAME}/etc
      - ./.home/run:/shared/${SERVER_NAME}/run
      - ./.home/etc:/etc/app
    depends_on:
      - uwsgi
      - granian
      - uvicorn
    ports:
      - '80:80'
      - '443:443'
    command: [
      holdup,
      -vt5,
      'unix:///var/app/run/uwsgi.sock',
      'unix:///var/app/run/granian.sock',
      'unix:///var/app/run/uvicorn.sock',
      --,
      nginx,
    ]
